<?php
 return array (
  1 => 
  array (
    'name' => '帮助中心',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'xinwen',
    'url' => '/zlyl/www//index.php?v=listing&cid=1&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  2 => 
  array (
    'name' => '新闻中心',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'xinwenyanshi2',
    'url' => '/zlyl/www//index.php?v=listing&cid=2&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  3 => 
  array (
    'name' => '图片',
    'pid' => '0',
    'child' => '1',
    'modelid' => '5',
    'catdir' => 'tupian',
    'url' => '/zlyl/www//index.php?v=listing&cid=3&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  4 => 
  array (
    'name' => '下载',
    'pid' => '0',
    'child' => '1',
    'modelid' => '6',
    'catdir' => 'xiazai',
    'url' => '/zlyl/www//index.php?v=listing&cid=4&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  31 => 
  array (
    'name' => '联系我们',
    'pid' => '29',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'lianxiwomen',
    'url' => '/index.php?v=listing&cid=31&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  6 => 
  array (
    'name' => '股票',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'gupiao',
    'url' => '/zlyl/www/index.php?v=listing&cid=6&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  7 => 
  array (
    'name' => '基金',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jijin',
    'url' => '/index.php?v=listing&cid=7&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  8 => 
  array (
    'name' => '保险',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'baoxian',
    'url' => '/index.php?v=listing&cid=8&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  9 => 
  array (
    'name' => '家族信托',
    'pid' => '1',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiazuxintuo',
    'url' => '/index.php?v=listing&cid=9&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  10 => 
  array (
    'name' => '房地产',
    'pid' => '2',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'fangdichan',
    'url' => '/index.php?v=listing&cid=10&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  11 => 
  array (
    'name' => '移民',
    'pid' => '2',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yimin',
    'url' => '/index.php?v=listing&cid=11&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  12 => 
  array (
    'name' => '项目投资',
    'pid' => '2',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'xiangmutouzi',
    'url' => '/index.php?v=listing&cid=12&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  14 => 
  array (
    'name' => '图片子栏目A',
    'pid' => '3',
    'child' => '0',
    'modelid' => '5',
    'catdir' => 'tu1',
    'url' => '/zlyl/www/index.php?v=listing&cid=14&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  15 => 
  array (
    'name' => '图片子栏目B',
    'pid' => '3',
    'child' => '0',
    'modelid' => '5',
    'catdir' => 'tu2',
    'url' => '/index.php?v=listing&cid=15&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  30 => 
  array (
    'name' => '关于我们',
    'pid' => '29',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'aboutus',
    'url' => '/zlyl/www/index.php?v=listing&cid=30&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  18 => 
  array (
    'name' => '下载子栏目A',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'catdir' => 'downa',
    'url' => '/index.php?v=listing&cid=18&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  29 => 
  array (
    'name' => '关于我们',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'guanyuwomen',
    'url' => '/zlyl/www/index.php?v=listing&cid=29&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  20 => 
  array (
    'name' => '下载子栏目B',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'catdir' => 'downb',
    'url' => '/index.php?v=listing&cid=20&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  32 => 
  array (
    'name' => '用户协议',
    'pid' => '29',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yonghuxieyi',
    'url' => '/index.php?v=listing&cid=32&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  28 => 
  array (
    'name' => '北京',
    'pid' => '0',
    'child' => '0',
    'modelid' => '3',
    'catdir' => 'beijing',
    'url' => '/index.php?v=listing&cid=28&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  27 => 
  array (
    'name' => '充值',
    'pid' => '0',
    'child' => '1',
    'modelid' => '2',
    'catdir' => 'tuangouyanshi',
    'url' => '/zlyl/www/index.php?v=listing&cid=27&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  26 => 
  array (
    'name' => '积分商城',
    'pid' => '0',
    'child' => '0',
    'modelid' => '8',
    'catdir' => 'jifenshangcheng',
    'url' => '/zlyl/www/index.php?v=listing&cid=26&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  33 => 
  array (
    'name' => '法律声明',
    'pid' => '29',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'falvshengming',
    'url' => '/index.php?v=listing&cid=33&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  35 => 
  array (
    'name' => '下载子栏目C',
    'pid' => '4',
    'child' => '0',
    'modelid' => '6',
    'catdir' => 'downc',
    'url' => '/index.php?v=listing&cid=35&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  36 => 
  array (
    'name' => '手机推广',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shoujituiguang',
    'url' => '/index.php?v=listing&cid=36&page=1',
    'showloop' => '0',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  37 => 
  array (
    'name' => '微信自动回复',
    'pid' => '0',
    'child' => '0',
    'modelid' => '22',
    'catdir' => 'weixinautoreply',
    'url' => '/index.php?v=listing&cid=37&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  40 => 
  array (
    'name' => '客服中心',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1000',
    'catdir' => 'kefu',
    'url' => '/zlyl/www/index.php?v=listing&cid=40&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  43 => 
  array (
    'name' => '建议反馈',
    'pid' => '40',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'jianyi',
    'url' => '/zlyl/www/index.php?v=listing&cid=43&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  44 => 
  array (
    'name' => 'BUG反馈',
    'pid' => '40',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'bug',
    'url' => '/zlyl/www/index.php?v=listing&cid=44&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  45 => 
  array (
    'name' => '在线客服',
    'pid' => '40',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'zxkefu',
    'url' => '/zlyl/www/index.php?v=listing&cid=45&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  46 => 
  array (
    'name' => '问题专区',
    'pid' => '40',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'wenti',
    'url' => '/zlyl/www/index.php?v=listing&cid=46&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  47 => 
  array (
    'name' => '举报不良信息',
    'pid' => '40',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'jbxx',
    'url' => '/zlyl/www/index.php?v=listing&cid=47&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  48 => 
  array (
    'name' => '举报外挂',
    'pid' => '40',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'jbwg',
    'url' => '/zlyl/www/index.php?v=listing&cid=48&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  49 => 
  array (
    'name' => '活动中心',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'hdzx',
    'url' => '/zlyl/www/index.php?v=listing&cid=49&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  50 => 
  array (
    'name' => '充值',
    'pid' => '27',
    'child' => '0',
    'modelid' => '0',
    'catdir' => 'chongzhi',
    'url' => 'http://localhost/PHP_PAY/index.php/',
    'showloop' => '1',
    'type' => '2',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  51 => 
  array (
    'name' => '官网客服',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'gwkf',
    'url' => '/zlyl/www/index.php?v=listing&cid=51&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  52 => 
  array (
    'name' => '建议反馈',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'gwjianyi',
    'url' => '/zlyl/www/index.php?v=listing&cid=52&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  53 => 
  array (
    'name' => 'BUG反馈',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'bug',
    'url' => '/zlyl/www/index.php?v=listing&cid=53&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  54 => 
  array (
    'name' => '问题专区',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'wenti',
    'url' => '/zlyl/www/index.php?v=listing&cid=54&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  55 => 
  array (
    'name' => '举报不良信息',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jbxx',
    'url' => '/zlyl/www/index.php?v=listing&cid=55&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  56 => 
  array (
    'name' => '举报外挂',
    'pid' => '51',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jbwg',
    'url' => '/zlyl/www/index.php?v=listing&cid=56',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  57 => 
  array (
    'name' => '客服专区',
    'pid' => '0',
    'child' => '0',
    'modelid' => '0',
    'catdir' => '',
    'url' => 'index.php?m=member&v=gwkf',
    'showloop' => '1',
    'type' => '2',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
)?>