<?php
 return array (
  'cid' => '58',
  'siteid' => '1',
  'keyid' => 'content',
  'name' => '国内新闻',
  'mb' => '',
  'catdir' => 'china ',
  'parentdir' => 'guanyuwomen',
  'pid' => '30',
  'type' => '0',
  'child' => '0',
  'modelid' => '2',
  'sort' => '0',
  'domain' => '',
  'url' => '/zlyl/www/index.php?v=listing&cid=58&page=1',
  'thumb' => '',
  'icon' => '',
  'workflowid' => '0',
  'showloop' => '1',
  'ismenu' => '1',
  'mshow' => '1',
  'listhtml' => '0',
  'showhtml' => '0',
  'listurl' => 'index.php?v=listing&cid={$cid}&page={$page}',
  'showurl' => 'index.php?v=show&cid={$cid}&id={$id}',
  'category_template' => '',
  'list_template' => '',
  'show_template' => '',
  'seo_title' => '',
  'seo_keywords' => '',
  'seo_description' => '',
  'ishot' => '0',
)?>